# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('direcction', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.CharField(max_length=500)),
                ('carreer', models.CharField(max_length=255)),
            ],
        ),
    ]
