# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-16 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catego',
            field=models.CharField(default='Nada', max_length=255),
        ),
    ]
