# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20170821_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
